### ISSUE TITLE
Funcionalidad del login y validación de las rutas 

### ISSUE THREAD

**Issue by asterisk747** [Desarrollo-de-aplicaciones-web-2024/proyecto-integrador-equipo-2#3]
- El login debe dejar ingresar a los usuarios registrados en al base de datos.
- Debe de redirigir a los usuarios a sus respectivas pantallas.
- El usuario autenticado debe de ser global en todo el sistema.
- Las pantallas no deben aceptar trafico no autenticado ni de otros usuarios ajenos a estas.

**Comment by POWRFULCOW89** [comment]
incluido en #5

**Comment by asterisk747** [comment]
Login funcional, y validacion de rutas en alumno
